config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resource :session, only: %i[new create destroy]
  resources :users do
    member do
      get :confirm_email
    end
  end
  root 'pages#about', as: 'home'
  get 'sessions/new', as: 'login'
  get 'users/index', as: 'all'
  get 'signings/services', as: 'service'
  get 'pages/gallery', as: 'photo'
  get 'pages/contacts', as: 'contacts'
  get 'signings/sign', as: 'zap'
  post 'signings/create_sign'
  post 'consultations/consult_response'
  get 'masters/show', as: 'masters'
  get 'works/prom', as: 'prom'
  get 'works/main', as: 'work'
  post 'works/test_page', as: 'worktest'
  get 'consultations/index', as: 'consult'
  get 'my_services/show', as: 'records'
  get 'reviews/show', as: 'comm'
  post 'reviews/new'
  post 'users/update'
  post 'users/create'
  get 'pages/guarantee', as: 'garant'
  get 'my_services/edit', as: 'edit_ord'
  post 'my_services/update', as: 'data_up'
end

app/models/work.rb
# frozen_string_literal: true

class Work < ApplicationRecord
  belongs_to :vacancy
  belongs_to :user
  enum male: %i[women man]
  validates :age, presence: true
  validates_numericality_of :age, only_integer: true, greater_than_or_equal_to: 18, less_than_or_equal_to: 70
  validates :male, presence: true
  validates :task_1, :task_2, :task_3, presence: true, length: { minimum: 10 }, format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/,
  message: 'Только русские буквы, цифры и спец символы' }
end

app/controllers/works_controller.rb
# frozen_string_literal: true

# to get job
class WorksController < ApplicationController
  before_action :autorize, only: :test_page
  include WorksHelper
  def main; end

  def prom; end

  def test_page
    @work = Work.new(about_form_params)
    @work.user_id = current_user.id
    @male = params[:male]
    @work.male = set_male(@male)
    return unless @work.valid?

    WorkMailer.with(user: current_user, work: @work).my_application_for_work.deliver_now
    @work.save
    flash[:notice] = 'Ваша заявка вскоре будет рассмотрена'
  end

  private

  def about_form_params
    params.permit(:vacancy_id, :age, :about, :task_1, :task_2, :task_3)
  end
end

app/helpers/works_helper.rb
# frozen_string_literal: true

module WorksHelper
  def set_male(male)
    case male
    when 'women'
      0
    when 'man'
      1
    end
  end
end

app/views/works/_tests_page.html.erb
 <%= form_with url: worktest_path do |form| %>
  <p><%= form.label :vacancy_id, "Выберите вакансию" %></p>
  <p><%= form.collection_select :vacancy_id, Vacancy.order(:title),:id,:title, include_blank: false %></p>
  <p><%= form.label :age, "Введите ваш возраст", id: 'age' %></p>
  <p><%= form.number_field :age, class: 'form-control' %></p>
  <p><%= form.label :male, "Выберите пол" %></p>
  <%= form.radio_button :male, 'women' %> Женщина
  <%= form.radio_button :male, 'man' %> Мужчина
  <p><%= form.label :about, "Расскажите о своих сильных и слабых сторонах" %></p>
  <p><%= form.text_field :about, class: 'form-control' %></p>
  <p><%= form.label :task_1, "Кем вы видите себя в нашей компании через 5 лет" %></p>
  <p><%= form.text_field :task_1, class: 'form-control' %></p>
  <p><%= form.label :task_2, "Почему вы выбрали именно наш автосервис" %></p>
  <p><%= form.text_field :task_2, class: 'form-control' %></p>
  <p><%= form.label :task_3, "Почему мы должны взять именно вас" %></p>
  <p><%= form.text_field :task_3, class: 'form-control' %></p>
  <p><%= form.submit("Оставить заявку", id: 'work_app') %></p>
<% end %>

<div id='zayavka_response-container'></div>

app/views/works/_zay_flash_response.html.erb
<div class='top'>
<% if @work.valid? %>
<div class='alert alert-info'>
        <strong id='msg'><%= flash[:notice] %></strong>
</div> 
<% else %>
  <ul>
    <% @work.errors.each do |error| %>
       <div class='alert alert-info'><li><%= error.full_message %></li></div>
    <% end %>
  </ul>
  <% end %>
 </div>

app/views/works/main.html.erb
 <h1>Преимущества работы у нас</h1>
 <div class="container">
  <div class="row align-items-start">

    <div class="col">
     <%= image_tag("house.jpg", height: '300', width: '300') %>
      <p><strong>ДОТАЦИИ НА ПРОЖИВАНИЕ</strong>
      <p>Для автомехаников и<br>
      диагностов, которые не имеют<br>
      своего жилья, мы делаем<br>
      дотацию в сумме<br>
      25 000 руб.<br>
      <strong>ежемесячно</strong>
    </div>

    <div class="col">
    <%= image_tag("money.jpg", height: '300', width: '300') %>
    <p><strong>Достойная оплата труда, выше рынка</strong>
    <p>Перед трудоустройством в нашу компанию у Вас будет возможность пообщаться с действующими<br> 
    сотрудниками и узнать о заработной плате, которую они получают, а так же о нашей системе мотивации.</p>
    У нас всё прозрачно и открыто. Мы понимаем, что<br>
    хорошим специалистам нужно хорошо платить,<br>
    поэтому зарплата наших сотрудников выше рынка.
    </div>

    <div class="col">
    <%= image_tag("carrier.jpg", height: '300', width: '300') %>
      <p><strong>Карьерный рост</strong>
      <p>В нашей компании хорошо отлажена система развития и карьерного роста сотрудников. Вы вполне можете вырасти от механика до управляющего одной из станций сервиса, или ТОП-менеджера управляющей компании.
      <p>Для Вашего роста созданы все условия, и мы ценим тех, кто хочет расти и идёт к своей цели.
      <p>Придя в нашу компанию, Вы лично познакомитесь с теми, кто прошёл путь от обычного механика, или водителя до руководителя сервиса.
    </div>

  </div>
</div>
 <div class='top'><div style="text-align: center;"><%= button_to "Оставить заявку", prom_path, method: :get, data: {turbo_frame: "frame1"}, class: 'form-control', id: 'work_btn'%></div></div>
<%= turbo_frame_tag "frame1" do%>
<div class="my-8 w-full mx-auto" id="content">
      <% render "tests_page" %>
  </div>
<%end%>

app/views/works/prom.html.erb
 <%= turbo_frame_tag "frame1" do %>
  <div class="my-8 w-full mx-auto" id="content">
    <%= render "tests_page" %>
  </div>
<% end %>
 

app/views/works/test_page.turbo_stream.erb
<%= turbo_stream.update 'zayavka_response-container', partial: 'zay_flash_response' %>