config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resource :session, only: %i[new create destroy]
  resources :users do
    member do
      get :confirm_email
    end
  end
  root 'pages#about', as: 'home'
  get 'sessions/new', as: 'login'
  get 'users/index', as: 'all'
  get 'signings/services', as: 'service'
  get 'pages/gallery', as: 'photo'
  get 'pages/contacts', as: 'contacts'
  get 'signings/sign', as: 'zap'
  post 'signings/create_sign'
  post 'consultations/consult_response'
  get 'masters/show', as: 'masters'
  get 'works/prom', as: 'prom'
  get 'works/main', as: 'work'
  post 'works/test_page', as: 'worktest'
  get 'consultations/index', as: 'consult'
  get 'my_services/show', as: 'records'
  get 'reviews/show', as: 'comm'
  post 'reviews/new'
  post 'users/update'
  post 'users/create'
  get 'pages/guarantee', as: 'garant'
  get 'my_services/edit', as: 'edit_ord'
  post 'my_services/update', as: 'data_up'
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/consultation.rb
# frozen_string_literal: true

class Consultation < ApplicationRecord
  belongs_to :user
  enum way: %i[tel pochta any]
  validates :body, presence: true, length: { minimum: 10 }, format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/,
  message: 'Только русские буквы, цифры и спец символы' }
  validates :way, presence: true
end

app/models/master.rb
# frozen_string_literal: true

class Master < ApplicationRecord
  has_many :service_records
  has_one_attached :face

  def mas_thumb(pic)
    pic.variant(resize_to_limit: [300, 300]).processed
  end
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  has_many_attached :photos
  belongs_to :user

  validates :body, presence: true, length: { minimum: 10 },
  format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/, message: 'Только русские буквы, цифры и спец символы' }
  def comm_thumb(pic)
    pic.variant(resize_to_limit: [300, 300]).processed
  end
end

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
  has_many :service_records
  validates :title, :description, :price, presence: true
  validates :title, uniqueness: true, format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/,
  message: 'Только русские буквы, цифры и спец символы' }
  validates :description, length: { minimum: 10 }, format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/,
  message: 'Только русские буквы, цифры и спец символы' }
  validates_numericality_of :price, only_integer: true, greater_than_or_equal_to: 1
end

app/models/service_point.rb
# frozen_string_literal: true

class ServicePoint < ApplicationRecord
  has_many :service_record
  validates :address, presence: true, length: { minimum: 10 }, uniqueness: true,
  format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/, message: 'Только русские буквы, цифры и спец символы' }
  validates :phone_number, presence: true, uniqueness: true, format: { with: /\A\+7\d{10}\z/,
  message: 'Начинается с +7 и только цифры(10 штук)' }
end

app/models/service_record.rb
# frozen_string_literal: true

class ServiceRecord < ApplicationRecord
  belongs_to :master
  belongs_to :user
  belongs_to :service
  belongs_to :service_point
  validates :date, :user_id, presence: true

  validate :date_cannot_be_in_the_past
  enum status: %i[prepared ready]
  has_many_attached :pictures

  def date_cannot_be_in_the_past
    errors.add(:date, 'не может быть в прошлом') if date.present? && date < Date.today
  end

  def picture_thumb(pic)
    pic.variant(resize_to_limit: [300, 300]).processed
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :old_password

  has_secure_password validations: false
  has_many :service_records
  has_many :consultations
  has_one :work
  has_many :reviews

  validates :email, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9.]+@[a-z]{2,6}\.[a-z]{2,3}\z/,
  message: 'Не верный формат' }
  validates :first_name, presence: true, format: { with: /\A[а-яА-Я\-]+\z/, message: 'Только русские буквы' }
  validates :second_name, presence: true, format: { with: /\A[а-яА-Я\-]+\z/, message: 'Только русские буквы' }
  validates :phone, presence: true, uniqueness: true, format: { with: /\A\+7\d{10}\z/,
  message: 'Начинается с +7 и только цифры(10 штук)' }

  validate :password_presence
  validate :correct_old_password, on: :update
  validates :password, confirmation: true, allow_blank: true

  before_create :confirmation_token

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(validate: false)
  end

  private

  def confirmation_token
    self.confirm_token = SecureRandom.urlsafe_base64.to_s if confirm_token.blank?
  end

  def correct_old_password
    return if BCrypt::Password.new(password_digest_was).is_password?(old_password)

    errors.add :old_password, 'Не верный'
  end

  def password_presence
    errors.add(:password, :blank) if password_digest.blank?
  end
end

app/models/vacancy.rb
# frozen_string_literal: true

class Vacancy < ApplicationRecord
  has_many :work
  validates :title, presence: true, uniqueness: true, format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/,
  message: 'Только русские буквы, цифры и спец символы' }
end

app/models/work.rb
# frozen_string_literal: true

class Work < ApplicationRecord
  belongs_to :vacancy
  belongs_to :user
  enum male: %i[women man]
  validates :age, presence: true
  validates_numericality_of :age, only_integer: true, greater_than_or_equal_to: 18, less_than_or_equal_to: 70
  validates :male, presence: true
  validates :task_1, :task_2, :task_3, presence: true, length: { minimum: 10 }, format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/,
  message: 'Только русские буквы, цифры и спец символы' }
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/masters_helper.rb
# frozen_string_literal: true

module MastersHelper
end

app/helpers/my_services_helper.rb
# frozen_string_literal: true

module MyServicesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/signings_helper.rb
# frozen_string_literal: true

module SigningsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      session[:user_id] = user.id
      flash[:success] = 'Добро пожаловать!'
      redirect_to home_path
    end
  end
end

app/helpers/works_helper.rb
# frozen_string_literal: true

module WorksHelper
  def set_male(male)
    case male
    when 'women'
      0
    when 'man'
      1
    end
  end
end

app/views/header/_header.html.erb
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom header">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
        <span class="fs-4"><strong><span class='white' id='home'>Cars feeling</span></strong></span><%= image_tag("toys.png", height:65, width: 65)%>
      <div class='text-right'>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-3 mb-md-0">
              <button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "О компании", home_path, class: 'nav-link px-2 text-white' %></button>
            <button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Услуги", service_path, class: 'nav-link px-2 text-white', id: 'signs' %></button>
            <button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Мастеры", masters_path, class: 'nav-link px-2 text-white' %></button>
            <button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Гарантии", garant_path, class: 'nav-link px-2 text-white' %></button>
            <button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Галерея", photo_path, class: 'nav-link px-2 text-white' %></button>
            <button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%=link_to "Работа у нас", work_path, class: 'nav-link px-2 text-white', id: 'work_pag' %>
            <button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Контакты", contacts_path, class: 'nav-link px-2 text-white', data: {turbo: false} %></button>
            <button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Отзывы", comm_path, class: 'nav-link px-2 text-white', id: 'revs' %></button>
         <% if user_signed_in? %>
                  <li class="nav-item dropdown mr-auto btn btn-outline-light me-2 text-bg-dark">
                    <a class="nav-link dropdown-toggle nav-link px-2 text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Аккаунт
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end text-bg-dark" aria-labelledby="navbarDropdown">
                      <li><%=link_to "Редактировать профиль",  edit_user_path(current_user), class: "nav-link px-2 text-white dropdown-item btn", type: "button"%></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><%=link_to "Мои заказы", records_path, class: "nav-link px-2 text-white dropdown-item btn", type: "button"%></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><%=link_to "Заказать конусльтацию", consult_path, class: "nav-link px-2 text-white dropdown-item btn", type: "button", id: 'cons_btn'%></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><%= button_to "Выйти", session_path, method: :delete, class: "nav-link px-2 text-white dropdown-item btn btn-lg", id: 'ex_btn'%></li>
                      </ul>
            <% else %>
            <button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Войти", login_path, class: 'nav-link px-2 text-white' %></button>
            <button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Зарегистрироваться", new_user_path, class: 'nav-link px-2 text-white' %></button>
            <% end %>
        </ul>
         </div>
      </a>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Car_Service</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <script src="https://api-maps.yandex.ru/2.1/?apikey=ваш API-ключ&lang=ru_RU">
	</script>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <%= javascript_include_tag "//www.google.com/jsapi" %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'header/header' %>
  <main class = "container">
    <% flash.each do |type, msg| %>
      <div class='alert alert-info'>
        <strong id='msg'><%= msg %></strong>
      </div> 
    <% end %>
    <%= yield %>
    </main>
          <%= render 'footer/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Автосервис Cars feeling</h1>
<h3>Миссия компании</h3>
Преобразование автосервисного рынка России до уровня лучших мировых стандартов, являясь на этом рынке лидером и новатором технологий

<div class='top'>
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("about.jpg", height: '700', width: '800', class: "d-block w-100", alt: "...") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("about2.jpg", height: '700', width: '800', class: "d-block w-100", alt: "...") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("about3.jpg", height: '700', width: '800', class: "d-block w-100", alt: "...") %>
    </div>
        <div class="carousel-item">
      <%= image_tag("about4.jpg", height: '700', width: '800', class: "d-block w-100", alt: "...") %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"  data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Предыдущий</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"  data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Следующий</span>
  </button>
</div>
</div>
<h3>Лучшие, потому что:</h3>
<ul>
<li>Современные</li>
Используем современные технологии и ставим интересы клиента на первое место.
<li>Оперативные</li>
Выполняем все поставленные задачи оперативно и в заявленные сроки.
<li>Надёжные</li>
Мы гарантируем, что автомобиль после обслуживания будет работать надёжно. Мы хотим, чтобы вы и ваши близкие чувствовали себя в безопасности.
<li>Открытые</li>
Вы всегда можете узнать, кто и что делает с вашим автомобилем — каждая станция оборудована камерами.
</ul>

app/views/pages/contacts.html.erb
<h1>Контакты</h1>
<ul>
<li>От станции м. Щелковская авт. №716, 716k, 1716 до конечной остановки "Посёлок Восточный"</li>
<li>Другие автобусы до остановки «Щитниково, д.146»</li>
<li>От станции м. Кунцевская авт. №305, 305k, 55 до конечной остановки "Посёлок Кунцево"</li>
<br />
<br />
<li>Время работы: с 8.00 до 21.30</li>
<br />
<li>Телефон: +7(916)384-91-19</li>
<li>Телефон: +7(927)709-14-12</li>
<li>E-mail: carsfeeling96@gmail.com</li>
</ul>
<h3>Карта</h3>
<div id="yandex_map" class="map">
</div>

app/views/pages/gallery.html.erb
<h1>Галерея</h1>
<div class='top'>
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("service_four.jpg", height: '700', width: '1200', class: "d-block w-100", alt: "...") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("service_two.jpg", height: '700', width: '1200', class: "d-block w-100", alt: "...") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("service_one.jpg", height: '700', width: '1200', class: "d-block w-100", alt: "...") %>
    </div>
        <div class="carousel-item">
      <%= image_tag("service_three.jpg", height: '700', width: '1200', class: "d-block w-100", alt: "...") %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"  data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Предыдущий</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"  data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Следующий</span>
  </button>
</div>
</div>

app/views/pages/guarantee.html.erb
<h3>Наши гарантии</h3>
<ul>
<li><h5>Почему мы уверены в своем качестве и даем 2 года гарантии на все услуги?</h5></li>
<li><h5>Почему цены ниже рынка?</h5></li>
<li><h5>А моя машина не станет еще хуже после вашего ремнота?</h5></li>
<li><h5>Такие молодые, как возможно практически без опыта сделать качественный ремонт?</h5></li>
<li><h5>Есть сомнения? Просто посмотрите видео от нашего руководителя</h5></li>
</ul>
<%= video_tag("video.mp4", :size => "1250x500", :controls => true) %>

app/views/pages/sign.html.erb
 <h1>Запись на обслуживание в Cars feeling</h1>
 <%= form_with url: "/pages/create_sign", method: :post do |form| %>
  <p><%= form.label :date, "Выберите дату" %></p>
  <p><%= form.date_select(:date, start_year: 2022, end_year: 2027, order: [:day, :month, :year], prompt: { day: 'Выберите день', month: 'Выберите месяц', year: 'Выберите год' }) %></p>
  <p><%= form.label :trouble, "Кратко опишите проблему(Не обязательное поле)" %></p>
  <p><%= form.text_field :trouble, class: 'form-control' %></p>
  <p><%= form.submit("Оставить заявку") %></p>
<% end %>

<div id='response-container'></div>