config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resource :session, only: %i[new create destroy]
  resources :users do
    member do
      get :confirm_email
    end
  end
  root 'pages#about', as: 'home'
  get 'sessions/new', as: 'login'
  get 'users/index', as: 'all'
  get 'signings/services', as: 'service'
  get 'pages/gallery', as: 'photo'
  get 'pages/contacts', as: 'contacts'
  get 'signings/sign', as: 'zap'
  post 'signings/create_sign'
  post 'consultations/consult_response'
  get 'masters/show', as: 'masters'
  get 'works/prom', as: 'prom'
  get 'works/main', as: 'work'
  post 'works/test_page', as: 'worktest'
  get 'consultations/index', as: 'consult'
  get 'my_services/show', as: 'records'
  get 'reviews/show', as: 'comm'
  post 'reviews/new'
  post 'users/update'
  post 'users/create'
  get 'pages/guarantee', as: 'garant'
  get 'my_services/edit', as: 'edit_ord'
  post 'my_services/update', as: 'data_up'
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/consultation.rb
# frozen_string_literal: true

class Consultation < ApplicationRecord
  belongs_to :user
  enum way: %i[tel pochta any]
  validates :body, presence: true, length: { minimum: 10 }, format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/,
  message: 'Только русские буквы, цифры и спец символы' }
  validates :way, presence: true
end

app/models/master.rb
# frozen_string_literal: true

class Master < ApplicationRecord
  has_many :service_records
  has_one_attached :face

  def mas_thumb(pic)
    pic.variant(resize_to_limit: [300, 300]).processed
  end
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  has_many_attached :photos
  belongs_to :user

  validates :body, presence: true, length: { minimum: 10 },
  format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/, message: 'Только русские буквы, цифры и спец символы' }
  def comm_thumb(pic)
    pic.variant(resize_to_limit: [300, 300]).processed
  end
end

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
  has_many :service_records
  validates :title, :description, :price, presence: true
  validates :title, uniqueness: true, format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/,
  message: 'Только русские буквы, цифры и спец символы' }
  validates :description, length: { minimum: 10 }, format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/,
  message: 'Только русские буквы, цифры и спец символы' }
  validates_numericality_of :price, only_integer: true, greater_than_or_equal_to: 1
end

app/models/service_point.rb
# frozen_string_literal: true

class ServicePoint < ApplicationRecord
  has_many :service_record
  validates :address, presence: true, length: { minimum: 10 }, uniqueness: true,
  format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/, message: 'Только русские буквы, цифры и спец символы' }
  validates :phone_number, presence: true, uniqueness: true, format: { with: /\A\+7\d{10}\z/,
  message: 'Начинается с +7 и только цифры(10 штук)' }
end

app/models/service_record.rb
# frozen_string_literal: true

class ServiceRecord < ApplicationRecord
  belongs_to :master
  belongs_to :user
  belongs_to :service
  belongs_to :service_point
  validates :date, :user_id, presence: true

  validate :date_cannot_be_in_the_past
  enum status: %i[prepared ready]
  has_many_attached :pictures

  def date_cannot_be_in_the_past
    errors.add(:date, 'не может быть в прошлом') if date.present? && date < Date.today
  end

  def picture_thumb(pic)
    pic.variant(resize_to_limit: [300, 300]).processed
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :old_password

  has_secure_password validations: false
  has_many :service_records
  has_many :consultations
  has_one :work
  has_many :reviews

  validates :email, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9.]+@[a-z]{2,6}\.[a-z]{2,3}\z/,
  message: 'Не верный формат' }
  validates :first_name, presence: true, format: { with: /\A[а-яА-Я\-]+\z/, message: 'Только русские буквы' }
  validates :second_name, presence: true, format: { with: /\A[а-яА-Я\-]+\z/, message: 'Только русские буквы' }
  validates :phone, presence: true, uniqueness: true, format: { with: /\A\+7\d{10}\z/,
  message: 'Начинается с +7 и только цифры(10 штук)' }

  validate :password_presence
  validate :correct_old_password, on: :update
  validates :password, confirmation: true, allow_blank: true

  before_create :confirmation_token

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(validate: false)
  end

  private

  def confirmation_token
    self.confirm_token = SecureRandom.urlsafe_base64.to_s if confirm_token.blank?
  end

  def correct_old_password
    return if BCrypt::Password.new(password_digest_was).is_password?(old_password)

    errors.add :old_password, 'Не верный'
  end

  def password_presence
    errors.add(:password, :blank) if password_digest.blank?
  end
end

app/models/vacancy.rb
# frozen_string_literal: true

class Vacancy < ApplicationRecord
  has_many :work
  validates :title, presence: true, uniqueness: true, format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/,
  message: 'Только русские буквы, цифры и спец символы' }
end

app/models/work.rb
# frozen_string_literal: true

class Work < ApplicationRecord
  belongs_to :vacancy
  belongs_to :user
  enum male: %i[women man]
  validates :age, presence: true
  validates_numericality_of :age, only_integer: true, greater_than_or_equal_to: 18, less_than_or_equal_to: 70
  validates :male, presence: true
  validates :task_1, :task_2, :task_3, presence: true, length: { minimum: 10 }, format: { with: /\A[а-яА-Я0-9,.!?:"'\-()\s]*\z/,
  message: 'Только русские буквы, цифры и спец символы' }
end

app/controllers/my_services_controller.rb
# frozen_string_literal: true

# to see your services and theirs status
class MyServicesController < ApplicationController
  before_action :check_user, only: :edit
  before_action :autorize, only: :show
  def show
    @my_services = ServiceRecord.where(user_id: current_user)
  end

  def edit
    session[:service_edit] = @service.id
  end

  def update
    @flag = false
    @service = ServiceRecord.find_by(id: session[:service_edit])
    return unless @service.update change_date_params

    @flag = true
    flash[:notice] = 'Дата записи обновлена'
  end

  private

  def check_user
    @service = ServiceRecord.find_by(id: params[:ord_id])
    redirect_to home_path if current_user.id != @service.user_id
  end

  def change_date_params
    params.permit(:date)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# controllin no action pages
class PagesController < ApplicationController
  def about; end

  def gallery; end

  def contacts; end

  def guarantee; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/masters_helper.rb
# frozen_string_literal: true

module MastersHelper
end

app/helpers/my_services_helper.rb
# frozen_string_literal: true

module MyServicesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/signings_helper.rb
# frozen_string_literal: true

module SigningsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      session[:user_id] = user.id
      flash[:success] = 'Добро пожаловать!'
      redirect_to home_path
    end
  end
end

app/helpers/works_helper.rb
# frozen_string_literal: true

module WorksHelper
  def set_male(male)
    case male
    when 'women'
      0
    when 'man'
      1
    end
  end
end

app/views/my_services/_update_page.html.erb
<div class='top'>
<% if @flag == true %>
<div class='alert alert-info'>
        <strong id='msg'><%= flash[:notice] %></strong>
</div> 
  <ul>
  <% else %>
    <% @service.errors.each do |error| %>
       <div class='alert alert-info'><li><%= error.full_message %></li></div>
    <% end %>
  </ul>
  <% end %>
 </div>

app/views/my_services/edit.html.erb
<div class='top'>
<h1>Ваш заказ</h1>
<p>Услуга: <%= Service.find_by(id: @service.service_id).title %></p>
    <p>Дата записи: <%= l @service.date, format: :long %></p>
    <p>Техцентр: <%= ServicePoint.find_by(id: @service.service_point_id).address %></p>
    <p>Номер телефона техцентра: <%= ServicePoint.find_by(id: @service.service_point_id).phone_number %></p>
    <p>Мастер: <%= Master.find_by(id: @service.master_id).fio %></p>
    <% if @service.trouble.size != 0 %>
    <p>Мой комментарий о проблеме: <%= @service.trouble %></p>
    <% end %>
     <% if @service.pictures.size != 0%>
    <p>Прикрепленные фотографии:</p>
    <% @service.pictures.each do |picture| %>
        <%= link_to image_tag(@service.picture_thumb(picture)), picture %>
    <% end %>
    <%end%>
    <p>Статус: <%= @service.status %></p>
<h1>Редактировать заказ</h1>
<%= form_with url: data_up_path, method: :post do |form| %>
  <p><%= form.label :date, "Выберите дату" %></p>
  <p><%= form.date_select(:date, start_year: 2022, end_year: 2027, order: [:day, :month, :year], default: Date.today ) %></p>
  <p><%= form.submit("Обновить", id: 'edit_rec') %></p>
<% end %>
<%= button_to 'К заказам', records_path, method: :get, class: 'form-control' %>
</div>
<div id='error_response-container'></div>

app/views/my_services/show.html.erb
<h3>Просмотр всех заказов</h3>
<h5>Можно изменять заказы за 3 дня и ранее до назначенной даты</h5>
<% k = 1 %>
<%@my_services.order(date: :desc).each do |record|%>
<div class='line'></div>
<h3><%= k %> Заказ:</h3>
    <p>Услуга: <%= Service.find_by(id: record.service_id).title %></p>
    <p>Дата записи: <%= l record.date, format: :long %></p>
    <p>Техцентр: <%= ServicePoint.find_by(id: record.service_point_id).address %></p>
    <p>Номер телефона техцентра: <%= ServicePoint.find_by(id: record.service_point_id).phone_number %></p>
    <p>Мастер: <%= Master.find_by(id: record.master_id).fio %></p>
    <% if record.trouble.size != 0 %>
    <p>Мой комментарий о проблеме: <%= record.trouble %></p>
    <% end %>
     <% if record.pictures.size != 0%>
    <p>Прикрепленные фотографии:</p>
    <% record.pictures.each do |picture| %>
        <%= link_to image_tag(record.picture_thumb(picture)), picture %>
    <% end %>
    <%end%>
    <p>Статус: <%= record.status %></p>
    <% if (record.date - DateTime.now.to_date).to_i > 3 %>
        <%= link_to 'Изменить заказ', edit_ord_path(ord_id: record.id), class: 'form-control', id: "id_#{k}" %>
        <% end %>
    <% k += 1 %>
<% end %>

app/views/my_services/update.turbo_stream.erb
<%= turbo_stream.update 'error_response-container', partial: 'update_page' %>